### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [HuangJunJie2017/Face-NMS#2]
您好，论文已读。有以下几点疑惑：
1. 算法1中的 m 以及相似度阈值是如何确定的？
2. 该方法是否会增加数据集中误分类样本的比重？

**Comment by HuangJunJie2017** [comment]
@ZHAIXINGZHAIYUE Thanks for your attention!
1.1 m ← argmin S ? m refers to the face in the current candidate pool with lowest similarity with the cluster center. 
1.2 The threshold is determined by the target scale of core set and is obtained by binary searching.
2.Yes, as Face-NMS tends to retain the faces away from the cluster center. If there is a clean set, I guess that 60% is not the lower bound.

**Comment by ZHAIXINGZHAIYUE** [comment]
感谢您的回复，对于m的含义是我误解了。另外：
1. 对于类别数较少的类，比如5，是否依然会做处理？
2. 对于所有的类别，都使用相同的阈值，是否合适？
3. 对于减少类别数，您有什么方法推荐吗？

**Comment by HuangJunJie2017** [comment]
@ZHAIXINGZHAIYUE 
1. we apply Face-NMS globally.
2. may not
3. recently, no~ it's much more complicate than intra-class......
